plugins:
  - jekyll-relative-links
  - jekyll-include-cache

relative_links:
  enabled: true
  collections: true

title: Peter's Woodworking

include:
  - index.md
  - gallery.md

theme: minima

header_links:
  - home.md
  - about.md